<script>
import Photos from "./components/Photos.vue";
import Photo from "./components/Photo.vue";
import Controls from "./components/Controls.vue";
import Info from "./components/Info.vue";
import { mapState } from "vuex";
import "./main.scss";
export default {
  name: "hot_or_not",
  components: {
    Photos,
    Photo,
    Controls,
    Info
  },
  created() {
    document.title = "Hot or Not?";
  },
  data() {
    return {
      lastBlobSize: undefined
    };
  },
  computed: {
    ...mapState(["infoScreenIsActive", "photos"])
  },
  updated: function() {
    if (this.photos.length <= 2) {
      this.getNewImages(10);
    }
  },
  methods: {
    fetchNewImage() {
      let url;
      const CORSProxy = "https://cors-anywhere.herokuapp.com/";
      const APIUrl = "https://thispersondoesnotexist.com/image";
      return fetch(CORSProxy + APIUrl, { cache: "no-store" })
        .then(response => response.blob())
        .then(blob => {
          if (this.lastBlobSize === blob.size) {
            // Duplicate response
            this.fetchNewImage();
          } else {
            this.lastBlobSize = blob.size;
            url = URL.createObjectURL(blob);
            this.$store.dispatch("addPhoto", {
              url: url,
              id: url.substring(url.lastIndexOf("/") + 1)
            });
          }
        });
    },
    async getNewImages(amount) {
      for (let i = 0; i < amount; i++) {
        await this.fetchNewImage();
      }
    },
    toggleInfoScreen() {
      this.$store.dispatch("toggleInfoScreen");
    }
  }
};
</script>

<template>
  <div id="app">
    <header class="header">
      <h1 class="title">
        <b>Hot</b> or not? You decide!
      </h1>
      <p
        class="subtitle"
      >All these people are not real and were generated by artificial intelligence. After you make your descision, this face will be sent to nonexistence, so don't expect to make a match :)</p>
      <button v-on:click="toggleInfoScreen()" class="show-info">
        <img :src="require('./icons/info.svg')" alt="Show additional info" />
      </button>
    </header>
    <main class="main">
      <Photos />
      <Controls />
    </main>
    <Info v-if="infoScreenIsActive" />
  </div>
</template>


